### ISSUE TITLE
can u update the mod?

### ISSUE THREAD

**Issue by Zakhaev31** [teralove/let-me-drink#3]
[mods] ERROR: Module "let-me-drink" could not be loaded!
[mods] ERROR: Please contact the module's author: https://discord.gg/659YbNY
Error: [dispatch] [let-me-drink] hook: Error: version 13 of message (name: "S_LOGIN", code: 58567) is outdated and cannot be used anymore
    at Dispatch.createHook (D:\Archivos de programa\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:247:27)
    at Dispatch.hook (D:\Archivos de programa\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:281:27)
    at Module.hook (D:\Archivos de programa\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:110:36)
    at new LetMeDrink (D:\Archivos de programa\TeraToolbox\mods\let-me-drink\index.js:38:6)
    at ModuleManager.load (D:\Archivos de programa\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:157:35)
    at D:\Archivos de programa\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:122:22
    at Map.forEach (<anonymous>)
    at ModuleManager.loadAll (D:\Archivos de programa\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\moduleManager.js:120:31)
    at Socket.<anonymous> (D:\Archivos de programa\TeraToolbox\bin\connectionManager.js:55:47)
    at Socket.emit (events.js:205:15)

**Comment by Zakhaev31** [comment]
fixed
